php55.json

Current PHP 5.5 repository URL does not exist, It is now being updated to a new URL.
Old URL : http://windows.php.net/downloads/releases/php-5.5.30-Win32-VC11-x86.zip
New URL : http://windows.php.net/downloads/releases/php-5.5.31-Win32-VC11-x86.zip

Update to PHP 5.5.31

---

php56.json

PHP 5.6.18 has been removed from the PHP download site in favor of the updated 5.6.19, leading to a PowerShell exception when attempting to install `php56`. This change simply updates the `php56` manifest to use the new 5.6.19 details.

Update PHP to 5.6.19

---

mysql56.json

Following up on lukesampson/scoop#749, this manifest adds a MySQL 5.6 (currently 5.6.29) manifest to allow installation of the previous version of MySQL if needed.

Add MySQL 5.6 app manifest

---

php53.json
php54.json
php55.json
php56.json

Following up on lukesampson/scoop#756, add the Visual C++ runtimes as a dependency when needed to older PHP versions. Specifically, only 64-bit version of PHP appear to need the DLL, with 32-bit versions working even if no Visual C++ runtime is installed.
Following up on lukesampson/scoop#757, add a command to the `post-install` scripts changing the `php.ini` configuration to look for extensions in an installation-relative folder, rather than looking in the default location, `C:\php\ext`, which makes the apps not work out-of-the-box and makes them less self-contained.
Update PHP 5.4 to 5.4.45, and 5.5 to 5.5.33. The current manifests return errors, since the referenced files no longer exist on the PHP download site. Also add a 64-bit architecture section to PHP 5.5, since there are 64-bit …

Update PHP versions and dependencies

---

apache24.json
mysql57.json
php70.json

Provides long-term support for PHP 7.0 and MySQL 5.7, so that even when the apps in the main bucket update a new major or minor version, the older versions will still be able to update to patch releases without breaking compatibility.
This proposed change is really just to open a discussion on the subject of including current versions of apps in this bucket. Especially with apps like PHP and MySQL that often include compatibility-breaking changes in minor releases, I believe it's prudent to include these manifests so that users don't have to uninstall the current version and install a previous one when the change finally does happen. This way, users who need to be guaranteed long-term support for something (like me, needing to sync development machines and production servers, which tend …

Add current versions of PHP/MySQL

---

php54.json
php55.json
php56.json
vc-redist11.json
vc-redist9.json

Following up on lukesampson/scoop#763 and lukesampson/scoop#766, this updates the previous PHP versions to use installers for their Visual C++ dependency, rather than direct downloading of DLLs.
(Sorry for the barrage of pull requests, just trying to get all this cleaned up)

Update previous PHP versions with Visual C++ installer dependencies

---

php55.json
php70.json

Following up on lukesampson/scoop#769. Also, remove the `vc-redist14` dependency, which apparently didn't get cleaned up in the last pull request.

Update PHP 7.0 to 7.0.5, 5.5 to 5.5.34

---

apache24.json

Following up on lukesampson/scoop#767.
(Side note, I’ve made these versioned aliases hardlinks between my local repositories, so they shouldn’t get out of sync again)

Remove separate app dependency for Apache 2.4

---

php70.json

Upgraded php version 7.0.5 to 7.0.6.
Windows.php.net removed version 7.0.5 which causes "scoop install php" to fail.
@lukesampson

upgraded 7.0.5 -> 7.0.6

---

php56.json

Files for versions 5.6.29 do not exist anymore. I updated to the latest 5.6.X files available.

Fix php 5.6 installation

---

tomcat6.json
tomcat7.json
tomcat80.json

As discussed in pull request [#385](https://github.com/lukesampson/scoop-extras/pull/385) for scoop-extras.

Add Tomcat 6.0, 7.0 and 8.0.

---

lynx283.json

Version 2.8.3 doesn't support SSL. The newly added [scoop/lynx 2.8.9dev.16](https://github.com/lukesampson/scoop/pull/2004) does.

Move lynx from main bucket to versions/lynx283

---

tomcat85.json

Note that Tomcat 8.5 is different from Tomcat 8.0.

Tomcat 8.5

---

bucket/7zip-beta.json
bucket/7zip-zstd.json

- 7zip-beta: Beta version of 7zip (maybe older than latest stable version, just latest "beta" version)
- 7zip-zstd: 7zip with Zstandard support
User could switch 7zip, 7zip-beta and 7zip-zstd by `scoop reset`.

Fix 7zip-beta and 7zip-zstd

---

bucket/python-beta.json
bucket/python27.json
bucket/python35.json
bucket/python36.json

- Change `python-beta` to only check "beta" versions
- Update `python27`, `python35`, `python36` manifests (`checkver`, `autoupdate.hash`)
- Fix `python35`, `python36`, `python-beta` `installer` and `uninstaller`, according to `python`'s
- When user has installed `python`, he wouldn't be able to install `python-beta` that has version prior to current stable, e.g., python=3.7.2 while python-beta=3.7.2rc1

Modify python27, python35, python36 and python-beta manifests

---

bucket/pwsh-beta.json

- Rename pwsh-prev to pwsh-beta so as to be consistent with other "beta version"s
- Fix manifest to only check `xxx-preview.x`("6.2.0-preview.3") or `xxx-rc.x`("6.1.0-rc.1")
- Change between stable and preview by `scoop reset`

Update pwsh-prev and rename

---

bucket/stunnel-beta.json
bucket/stunnel549.json

- Add stunnel-beta
- Rename stunel5.49 to stunel549, add `uninstaller.script`, remove `checkver` and `autoupdate`, since it is the latest version that support win32.

stunnel: Add stunnel-beta and rename stunnel 5.49

---

bucket/php54.json
bucket/php56.json

- php54: Change hash to sha256 since this version is frozen
- php56: Change hash extraction to sha256

php: Fix php54 and php56

---

bucket/openssl10.json

- Rename from `openssl10x` to `openssl10` as to be consistent with other one's name
- Change license
- Change `hash` and `checkver` to default sha256

Rename and mod openssl10

---

bin/auto-pr.ps1
bucket/mysql56.json
bucket/mysql57.json
bucket/pwsh-beta.json
bucket/rclone-beta.json
bucket/tomcat7.json
bucket/tomcat85.json

Hi,
The outdated tomcat85 files are no more available, I run the autoupdate script to update it and now it seems to work.
Also `auto-pr` seems to work a little strange. Is there an instruction on how to use it?
Also, there was a mistake in a path to `bucket` folder in it.
Thanks

 Update tomcat and others by autoupdate

---

bucket/python-beta.json
bucket/python27-beta.json
bucket/python35.json
bucket/python36.json

- Fix `checkver` in python manifests that may give wrong updated version that don't have binary files.
- Add `python27-beta`

Python: Fix checkver error

---

bucket/python-alpha.json

- python-alpha check alpha and beta versions (3.8.0a2)
- python-beta check rc versions (3.7.3rc1)

python: Seperate python-alpha and python-beta

---

bucket/python27.json

Retrieved from https://www.python.org/downloads/release/python-2716/

Update Python 2.7 installer hash

---

bucket/mariadb103.json

Adds [latest stable version](https://downloads.mariadb.org/mariadb/+releases/) of MariaDB 10.3 (10.3.18)
> _MariaDB 10.3 is the previous major stable version. The first stable release was in May 2018, and it will be supported until May 2023._
> https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-103/

Add MariaDB 10.3

---

bucket/pwsh-beta.json

@r15ch13
With Powershell 7 the naming convention is changing from 6.2.3 "Powershell Core" to just "Powershell", therefore the shortcut name should reflect that.
Also, while not edited, should future betas (7.1+) have this make the shims "pwsh-preview.exe" to allow for side-by-side?

pwsh-beta: Change shortcut name

---

bucket/ruby26.json

Source: https://github.com/ScoopInstaller/Main/blob/ad61ac28d0b811fbaf31986eabd2986a5b6ca631/bucket/ruby.json
Edited to specify 2.6.x in the `checkver`.

Add ruby26 at 2.6.5-1

---

bucket/helm2.json

The main bucket now has the latest helm release: helm3.
Majority helm2 users would now (or soon) be in the process of migrating their helm2 managed workloads to helm3, and having them both side-by-side makes the process very convenient.

helm2: add new shim 'helm2'

---

bucket/spotbugs-beta.json

[SpotBugs](https://spotbugs.github.io/) is a static analysis tool for Java code. It comes with a command-line interface and a GUI.
Although 4.0.2 *is* currently the latest release of SpotBugs, when there are newer betas or release candidates available, this manifest will automatically update to them (see https://github.com/spotbugs/spotbugs/releases).

spotbugs-beta: Add version 4.0.2

---

bucket/dotnet-sdk-preview.json

Before this fix the the dotnet path was not working correctly with the IDE Rider as it could not find the path to the sdk.

dotnet-sdk-preview: Fixing path

---

bucket/postman-canary.json

I noticed Postman's canary channel wasn't available in scoop and I wanted to use it. That's pretty much all there is to it.

postman-canary: Add version 7.36.0-canary02

---

bucket/anaconda2.json
bucket/miniconda2.json

Address an issue with `checkver` as of lukesampson/scoop-extras#5197 and lukesampson/scoop-extras#4598.
Maybe should consider adding `miniconda37` as well:

anaconda2/miniconda2: Fix checkver

---

bucket/7zip-beta.json

- Changed URLs from MSI to EXE for a slightly smaller file size. 
The unzipped contents appear to be identical.
- License(s) updated. Previously lacked the BSD 3-Clause (due to code derived from Apple's "LZFSE compression library") and UnRAR licenses.
- Are MSIs preferred when the assembly is unsigned?
- I find it a little strange the auto-updater didn't catch the latest beta release. That may need to be investigated.
- URLs pulled from https://7-Zip.org/Download.html and https://sourceforge.net/p/sevenzip/discussion/45797/thread/9f5b067368/
- I was also going to add the URL and SHA256 for the ARM64 release, but Scoop's ARM64 specs haven't been finalized just yet.

7zip-beta: Update to 21.03

---

bucket/putty-cac.json

Add PuTTY CAC (with CAPI and PKCS support).

putty-cac: Add version 0.76u1

---

bucket/dotnet-sdk-preview.json

Release candidate is a kind of preview as well, and it was not on the checkver jsonpath

dotnet-sdk-preview: Add the possibility to get RC versions as well

---

bucket/wox-beta.json

The `extras` bucket already has the latest release Wox v1.3.524, however it was [released](https://github.com/Wox-launcher/Wox/releases/tag/v1.3.524) more than 3 years ago. The latest [pre-release v1.4.1196](https://github.com/Wox-launcher/Wox/releases/tag/v1.4.1196) is about a year old, it includes nice improvement in search speeds, many customizations in UI since the latest release, but also for me it fixed a critical bug on Windows 10 that made app unusable after computer is being put into Sleep mode.
I suggest to add this version as a beta, since `autoupdate` ignores pre-releases, but the Wox's maintainers neither update the latest release nor add more pre-releases
I used the original [`wox.json`](https://github.com/lukesampson/scoop-extras/blob/b3c4b46dda148ef40a29e83723925659b19a57a6 …

wox: Add Wox-beta, i.e. pre-release v1.4.1196

---

bucket/gcc-llvm-ucrt.json
bucket/gcc-llvm.json
bucket/gcc-msys.json
bucket/gcc-ucrt.json

- gcc-msys: Original gcc from `Main`
- gcc-llvm: WinLibs build w/ LLVM/Clang/LLD/LLDB
- gcc-ucrt: WInLibs build w/ UCRT runtime
- gcc-llvm-ucrt: WinLibs build w/ LLVM/Clang/LLD/LLDB & UCRT runtime

gcc: Add some alternative versions

---

bucket/beef-nightly.json

Supersedes #227.
This adds the nightly version of *beef* compiler.

beef-nightly: Add version 0.43.1.11182021

---

bucket/android-studio-beta.json
bucket/android-studio-canary.json

Closes #274
Largely based on Android Studio stable in Extras https://github.com/ScoopInstaller/Extras/blob/master/bucket/android-studio.json
Adding both Beta and Canary in one go because their manifests are so similar.

Add Android Studio Beta & Canary

---

bucket/openssl-light.json

As of v3.0.0 OpenSSL is published under Apache License 2.0

openssl-light: fix license

---

bucket/love10.json
bucket/love6.json
bucket/love7.json
bucket/love8.json
bucket/love9.json

Here are the changes:
- consistent descriptions and shortcuts
- fix dead download links (repo moved from bitbucket to github)
- removed autoupdate & checkvers because unlikely that updates will release for old versions, also couldn't find a way to checkver on github releases for versions that aren't the latest or via the atom xml which doesn't have every old release

Cleanup LÖVE manifests

---

bucket/oh-my-posh2.json

oh-my-posh v2 is archived to https://github.com/JanDeDobbeleer/oh-my-posh2 and scoop extras bucket remove it.
So it should be add to this.

oh-my-posh2: Add version 2.0.496

---

bucket/gimp-dev.json

- Closes #361
- Based on https://github.com/ScoopInstaller/Extras/blob/master/bucket/gimp.json
- Commented out the section for pygimp.env in installer because no longer present in v2.99+

gimp-dev: add version 2.99.8

---

bucket/xmind8.json

[XMind 8](https://www.xmind.net/xmind8-pro/) is no longer updated, but is still available. [XMind](https://www.xmind.net/) is the recommended version.
Relates to https://github.com/ScoopInstaller/Extras/pull/3609

xmind8: Add version 3.7.9

---

bucket/firefox-nightly.json

Updated `firefox-nightly` to use a persistent profile directory 
Relates to ScoopInstaller/Extras#7573

chore: firefox-nightly portable config

---

bucket/clion-eap.json
bucket/clion-rc.json
bucket/datagrip-eap.json
bucket/datagrip-rc.json
bucket/dataspell-eap.json
bucket/dataspell-rc.json
bucket/goland-eap.json
bucket/goland-rc.json
bucket/idea-eap.json
bucket/idea-rc.json
bucket/idea-ultimate-eap.json
bucket/idea-ultimate-rc.json
bucket/mps-eap.json
bucket/phpstorm-eap.json
bucket/phpstorm-rc.json
bucket/pycharm-eap.json
bucket/pycharm-professional-eap.json
bucket/pycharm-professional-rc.json
bucket/pycharm-rc.json
bucket/rider-eap.json
bucket/rubymine-eap.json
bucket/teamcity-eap.json
bucket/teamcity-rc.json
bucket/webstorm-eap.json
scripts/jetbrains/portable.ps1

This adds RC (release condidate) and EAP (early access program) of **JetBrains** apps to the bucket.
Notes:
* I have (1) run autoupdate locally, (2) installed, and (3) run the software of all these packages, to make sure they work properly.

Jetbrains apps: Add RC and EAP packages

---

bucket/windowsdesktop-runtime-lts.json

.NET Desktop Runtime has change its download URLs for version 6
Closes #388

windowsdesktop-runtime-lts: Fix download URLs

---

bucket/gpac-nightly.json

Related: https://github.com/ScoopInstaller/Main/pull/3226
Related: https://github.com/ScoopInstaller/Main/pull/1246
This adds the nightly version of **GPAC** to the bucket.

gpac-nightly: Add version 1.1.0-DEV-rev1648

---

bucket/okular.json

Fixes Okular's shortcut name not being capitalised in the start menu shortcut. Closes #409

Fix Okular's shortcut in the start menu not being capitalised

---

bucket/avidemux-nightly.json

- Relates to https://github.com/ScoopInstaller/Extras/pull/7926
- So users can test the next version of Avidemux
- No hashes available

avidemux-nightly: add version 220130

---

bucket/gradle5.json
bucket/gradle6.json

I verified the installation process with my fork: both hash checks pass and with both `gradle --version` works.
Closes #417

gradle: add version 5 and 6

---

bucket/firefox-beta.json
bucket/firefox-developer.json
bucket/firefox-nightly.json

use $persist_dir instead of $dir in profile path, then profile path can still be used in other versions after uninstalling the apps. (if it is compatible)
- this change only affects fresh installations.
- for users who have generated a scoop portable profile before this update, you will need to manually edit this file **OR** delete it and reinstall the application to change the profile path, if you want use uninstalled app's profile:
```
$HOME\AppData\Roaming\Mozilla\Firefox\profiles.ini
```

*mozilla: use $persist_dir instead of $dir in profile path

---

bucket/openscad-dev.json

- Closes #385
- New `checkver` script similar to my scripts for kodi-nightly, inkscape, vlc-nightly
- Shortcut moved from `post_install` as https://github.com/openscad/openscad/issues/1309 has now been fixed
- Hash is now sha512

openscad-dev: update to v.2022.03.08, fix checkver

---

bucket/keepassxc2.6.6.json

Relates to [Extras#8184](https://github.com/ScoopInstaller/Extras/pull/8184)
KeepassXC for 32-bit Windows is no longer supported after v2.6.6, so move keepassxc version v2.6.6 to Version Bucket.
The checkver and autoupdate had been removed.

keepassxc2.6.6: Add version 2.6.6

---

bucket/1password-cli1.json

Version 2 of 1password-cli breaks backward compatibility and introduce new CLI syntax. Having older version available is useful for those who don't want or can't upgrade to version 2 right now.

Add 1password-cli v1

---

bucket/tinymediamanager3.json

* related: https://github.com/ScoopInstaller/Extras/issues/4821
* tinyMediaManager switched to 64-bit in version 4, but it is **32-bit** in version 3.
* **why do we need this package**: From version 4, tinyMediaManager has changed its licensing model from donationware to subscription based. [tinyMediaManager blog](https://www.tinymediamanager.org/blog/v4-future/):
> Since the lion’s share of the work (development, maintenance, deployment, …) remains within the tinyMediaManager team, we decided to charge an annual fee for the ongoing work on the project (starting with v4).
> tinyMediaManager v3 will remain available and free, but only serious bugs will be fixed and no new features will be added. A mandatory upgrade to v4 will not be necessary, but we want to provide an easy transition for …

tinymediamanager3: Add version 3.1.16.1

---

bucket/oss-cad-suite-nightly.json

- Adds OSS CAD Suite which only has a nightly release. I would like to add it because Main/yosys is out of date (0.9 while latest is 0.15) and this package includes it and seems to be released by the same people.
- Relates to Excavator failure to update yosys https://github.com/ScoopInstaller/Main/runs/5709628840?check_suite_focus=true#step:3:338 (I will make another PR to add a note to yosys)
- The package includes a batch file that changes the environment variables temporarily for the programs included. I decided to create a shim to that rather than persist the variables permanently because they would override Python, Qt, and GTK variables that other programs use.

oss-cad-suite-nightly: Add version 2022-03-29

---

bucket/gn.json

This makes **"version"** more readable and less confusing.
(`qGN3VImiZx7eJqi6ER9-ZPt3RASJhtJm0CgN4oVbAQcC` -> `qGN3VI`)

gn: Use first 6 chars of instanceID as version

---

bucket/cosmosdbexplorer-beta.json

- Relates to #479
- Manifest mostly written by @aloneguid, had to open new PR because couldn't suggest file name change in GitHub's PR review feature
- Added 64bit architecture
- Updated checkver to get only beta versions (will need to add to Extras if/when it comes out of beta)
- Added 'Beta' to shortcut so as not to clash with any future stable releases

cosmosdbexplorer-beta: Add version 0.9.0

---

bucket/goneovim-nightly.json

gooneovim-nightly will set the output of `git describe --tags` to the version.
refs: https://github.com/akiyosi/goneovim/blob/master/.github/workflows/ci.yaml#L87
`git describe --tags` will output the following format
```
<tagname>-<the number of additional commits>-g<commit hash>
```
refs: https://git-scm.com/docs/git-describe
Since goneovim-nightly builds HEAD, the number of additional commits is `1`. Therefore, the version should be set to `nightly-1-g<commit hash>`.

goneovim-nightly: fix version

---

bucket/everything-alpha.json

- fix persist
- move `install-context.reg` generate script to `post_install` then the path replaced with `current` instead of `$version`
Closes #485

everything-alpha: Update manifest

---

bucket/ferdium-nightly.json

`$baseurl/latest.yml` only have hashes for `Ferdium-Setup-$version.exe` and not `Ferdium-$version.exe`. This PR switches the manifest to using the setup executable, so we can take advantage of hash extraction.
Related to #497

ferdium-nightly: fix failed hash verification

---

bucket/dotnet3-sdk.json

Relates to Excavator unable to update: https://github.com/ScoopInstaller/Versions/runs/6296827221?check_suite_focus=true#step:3:196

dotnet3-sdk: Update to v3.1.418, fix checkver

---

bucket/kdenlive-nightly.json

- Adds Nightly version of Kdenlive in extras.
- Similar to okular-nightly: https://github.com/ScoopInstaller/Versions/blob/master/bucket/okular-nightly.json

kdenlive-nightly: Add version 1116

---

bucket/arduino-ide-rc.json

closes #504
This adds [Arduino IDE](https://www.arduino.cc/en/software) version 2.0 (currently in RC stage)
**NOTES**:
* The stable version (version 1.8.19) exists in *Extras* bucket. (`extras/arduino`).
* I named the package as `arduino-ide` rather than `arduino` because the repo name for ver 2.0 is ["arduino-ide"](https://github.com/arduino/arduino-ide).
* *persist* is not needed because config is at `$Env:AppData\Arduino IDE`.
* [stable.yml](https://github.com/arduino/arduino-ide/releases/download/2.0.0-rc6/stable.yml) only contains SHA-512 hash for exe installer, but not for the ZIP file.

arduino-ide-rc: Add version 2.0.0-rc6

---

bucket/greenshot-unstable.json

- Relates to Excavator unable to update due to lack of trailing slash in url: https://github.com/ScoopInstaller/Versions/runs/6384644377?check_suite_focus=true#step:3:196
- Was stuck at release from 16 Dec 2021: https://github.com/greenshot/greenshot/releases/tag/v1.3.220

greenshot-unstable: Update to 1.3.249, fix checkver

---

bucket/msys2-20200517.json

Relates to Excavator looking for updates despite the fact this app shouldn't be updated as higher versions do not have a 32bit release. See: https://github.com/ScoopInstaller/Versions/pull/209
> This PR adds version 20200517 of msys2 as requested, which is the last version that includes i686 package.

msys2-20200517: Remove checkver

---

bucket/helm2.json

- Relates to Excavator unable to update: https://github.com/ScoopInstaller/Versions/runs/6384644377?check_suite_focus=true#step:3:227
- Added End of Life note.
- Should we remove checkver too?

helm2: Update to version 2.17.0, fix checkver

---

bucket/dataspell-eap.json

Relates to Excavator unable to update due to file url change: https://github.com/ScoopInstaller/Versions/runs/6384644377?check_suite_focus=true#step:3:263

dataspell-eap: Update to 2022.1-221.4994.58, fix autoupdate

---

bucket/dotnet5-sdk.json

- Relates to Excavator unable to update: https://github.com/ScoopInstaller/Versions/runs/6413290805?check_suite_focus=true#step:3:207
- Based on checkver from dotnet3-sdk: https://github.com/ScoopInstaller/Versions/blob/master/bucket/dotnet3-sdk.json

dotnet5-sdk: Update to v5.0.408, fix checkver

---

bucket/openssl1-light.json
bucket/openssl1.json

- Relates to #524
- OpenSSL 1.x branch is now higher than 1.0 so the manifests needed to be renamed and the checkvers needed to be fixed

openssl10|-light: Rename to openssl1 and update to 1.1.1o

---

bucket/musescore3-nightly.json

Relates to #526 where I said I would add this version too. Both this branch and the latest branch are offered on the development builds page: https://ftp.osuosl.org/pub/musescore-nightlies/. It's based on the `musescore-nightly` manifest. Sadly no hash extraction.

musescore3-nightly: Add version 202205130434

---

bucket/musescore-nightly.json

- Relates to Excavator stuck on version from 2020! https://github.com/ScoopInstaller/Versions/runs/6413290805?check_suite_focus=true#step:3:245
- Fixed checkver and autoupdate
- Fixed bin and shortcuts file name
- Added extract_dir to autoupdate
- Updated license to GPL 3
- Will need to be updated once 5.x branch begins releases, I will also make a PR for the 3.x nightly

musescore-nightly: Update to version 202205130439

---

bucket/ngrok2.json

Relates to https://github.com/ScoopInstaller/Main/issues/3603.
ngrok version 3 has breaking changes listed here: https://ngrok.com/docs/guides/upgrade-v2-v3. For that reason it would be good to keep the 2.x branch in case anyone needs it. I haven't found any documentation that says v2 is no longer receiving updates so I've left the original checkver/autoupdate.

ngrok2: Add version 2.3.40

---

bucket/de4dot-net35.json
bucket/de4dot-net45.json
bucket/de4dot-netcoreapp3.1.json

**[de4dot](https://github.com/de4dot/de4dot)** is a .NET deobfuscator and unpacker. It is now archived, but still [being used by some projects](https://github.com/de4dot/de4dot/network/dependents?package_id=UGFja2FnZS0xNTc3NDA1NTg%3D).
* There are 3 variants of the app (for different .NET versions). I put all of them in `Versions` bucket because I am not sure which one should be considered the **"main"** one.
* `de4dot-net35` and `de4dot-net45` provides both **32-bit** and **64-bit** binaries, but `de4dot-netcoreapp3.1` only has the 64-bit one.
* The version number `3.1.41592.3405` can be found either in **file info** of the executable, or [build config file](https://github.com/de4dot/de4dot/blob/master/De4DotCommon.props).
* *de4dot* provides pre-built binaries via Github actions, but it …

de4dot: Add version 3.1.41592.3405

---

bucket/processhacker-nightly.json

They removed the `v` prefix in tags starting with https://github.com/ProcessHackerRepoTool/nightly-builds-mirror/releases/tag/3.0.4922.

processhacker-nightly: Update to version 3.0.4953, Update checkver

---

bucket/odin-dev.json
bucket/odin.json

I was going through the GitHub Actions logs and noticed that the update for Odin was failing. This was because the autoupdate URL is no longer valid (it turns out the Odin team has changed the naming convention for their release artifacts). 
This PR updates the issue with the autoupdate URL. I also took the opportunity to manually update the version, as well as renaming `odin → odin-dev`. 
I'm a bit unsure whether doing this rename is a good idea (considering there might be other users already using `odin`. But I think `odin-dev` is a better name for it, since these are the dev releases. If we left it as `odin` then there might be confusion when/if somebody adds stable `odin` to Scoop/main. Let me know if this change is ok.
btw, since this is a small change I didn't create an issue for …

odin: Update version, fix autoupdate url, and change name to odin-dev

---

bucket/odin-nightly.json

Since we've got Odin Dev version, I noticed the website offers a nightly version too. The page for downloads is here: https://odin-lang.org/docs/nightly/ but it requires JavaScript to load the links, so the checkver gets it directly from the source which is a json file. Same otherwise as `odin-dev`.

odin-nightly: Add version 2022-06-28

---

bucket/smplayer-with-smtube.json

* supersedes https://github.com/ScoopInstaller/Extras/pull/8770
* closes https://github.com/ScoopInstaller/Extras/pull/8734
* See [comment on the SMTube PR](https://github.com/ScoopInstaller/Extras/pull/8734#discussion_r904462308) for details.
* The package is modified based on [extras/smplayer](https://github.com/ScoopInstaller/Extras/blob/master/bucket/smplayer.json).

smplayer-with-smtube: Add version 22.2.0.0-smtube21.10.0

---

bucket/ferdium-nightly.json

Update URL to match new naming convention introduced in ferdium-nightly 6.0.0-nightly.84, and update manifest to 6.0.0-nightly.85. Closes #569

ferdium-nightly: Fix URL, update to 6.0.0-nightly.85

---

bucket/calibre-normal5.json

Calibre drops support for 32-bit CPUs after v6.0.0, if you are running a 64-bit system, please download `calibre-normal` from Scoop Extra bucket.
Relates to [Extras#8853](https://github.com/ScoopInstaller/Extras/pull/8853)

calibre-normal5: Add version 5.44.0

---

bucket/1password-cli1.json

- Updated 1password-cli1 (v1) to include autoupdate/checkver based on the manifest of 1password-cli v2 (in main bucket)
- Bumped version from 1.12.4 to 1.12.5
- Validated autoupdate with checkver.ps1, and validated install of latest 1.12.5 version

1password-cli1: Update to version 1.12.5, Add checkver/autoupdate

---

bucket/discord-ptb.json

* related: #598
* Using **PortApps** as file source (same as `extras/discord`) because the files extracted from official installer (https://dl-ptb.discordapp.net/distro/app/ptb/win/x86/1.0.1017/DiscordPTBSetup.exe) would not work without setting up the service.

discord-ptb: Update to version 1.0.1015-19, Fix autoupdate

---

bucket/greenshot-unstable.json

Official website (https://getgreenshot.org/version-history/) is quite a few versions behind, so I updated the `checkver` URL to GitHub releases.

greenshot-unstable: Update to version 1.3.270

---

bucket/spark-hadoop2.json
bucket/spark-scala2.13.json
bucket/spark-without-hadoop.json

Relates to Spark package in Main being out of date. Version 3.3.0 has been released but the current Main package is set up for the version with Hadoop 2, which is no longer the default. This PR moves the Main package here as `spark-hadoop2` so that the Main package can be updated to the default download with Hadoop 3.
This PR also adds a version with Hadoop 3 & Scala 2.13 and a version bundled without Hadoop, which are available [here](https://spark.apache.org/downloads.html)
After this is merged, [Main #3871](https://github.com/ScoopInstaller/Main/pull/3871) can be merged.

spark-*: Add other versions with/without Hadoop

---

bucket/nheko-nightly.json

Previously, autoupdate failed for nheko (and nheko failure caused failure of all other auto-updates) due to regex not matching. This PR allows for single-digit dates in regex so that matching is successful. 
Closes #642

nheko@nightly: allow 1- or 2-digit regex to fix autoupdate failure

---

bucket/multipar-beta.json

`par2_rename.exe` is removed and some python scripts are added in version 1.3.2.5.

multipar-beta: Remove deprecated bin

---

bucket/kdeconnect-nightly.json

Relates to [Extras/#9304](https://github.com/ScoopInstaller/Extras/pull/9304)
Based on [okular-nightly.json](https://github.com/ScoopInstaller/Versions/blob/master/bucket/okular-nightly.json)

kdeconnect-nightly: Add version 1291

---

bucket/olive-editor-nightly.json

This fixes `olive-editor-nightly` install by updating the download URL following the new standards on their repo. Also removes the workaround for extracting the `.zip.zip` file, as that's no longer needed.
Closes #660

fix olive-editor-nightly (fixes #660)

---

bucket/tinymediamanager3.json

**Also removed checkver and autoupdate blocks, because this version of the tinymediamanager is no longer maintained.**
Closes #691

tinymediamanager3: Fix URL and Hash

---

bucket/logseq-nightly.json

logseq-nightly: Update to 0.8.8-20221007

---

bucket/putty-cac.json

Update putty-cac to version 0.77u1. Existing `checkver` and `autoupdate` should work, though.

putty-cac: Update to version 0.77u1

---

bucket/ipfilter-nightly.json

[It's in extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/ipfilter-updater.json)

ipfilter-nightly: Add version 2022-07-30

---

bucket/goneovim-nightly.json

Remove `nightly` from the version so that it can be updated with `scoop update`.
Also, since the datetime string is not converted at https://github.com/ScoopInstaller/Scoop/pull/5130, `jsonpath` and `regex` are also changed.

goneovim-nightly: Fix checkver

---

bucket/neovim-nightly.json

Fix checkver to get new version format (add back '+' in the middle) by reverting the changes introduced by c7e95134d15b73b1886556d43f4b272a7ae62500
Relates to #719. ghomb mentions that "the Scoop repository has the latest version 0.9.0-dev-98-g1c478391c while the Neovim repository has the latest version of v0.9.0-dev-143+ga288b4f21."

neovim-nightly: Fix chechver

---

bucket/mpv.net-beta.json

They now add "-beta" to the end of the beta GitHub releases as well it seems

mpv.net-beta: Update to version 6.0.3.2, update URLs

---

bucket/everything-alpha.json

Fixes this error I personally had with **everything-alpha** during the installation process.

everything-alpha: Fix `pre_install` script

---

bucket/yt-dlp-daily.json

[It's in main](https://github.com/ScoopInstaller/Main/blob/master/bucket/yt-dlp.json)

yt-dlp-daily: Add version 2022.11.06.334

---

bucket/duplicati-canary.json

Relates to https://github.com/ScoopInstaller/Extras/pull/9533

duplicati-canary: Fix `notes`, and fix `pre_uninstall`

---

bucket/ipfilter-nightly.json

Changed date format to unix timestamp for better accuracy

ipfilter-nightly: Unix timestamp checkver

---

bucket/ffmpeg-nightly.json

ffmpeg-nightly: Fix checkver, moved to `/latest` builds, Update to version 1669382325

---

bucket/anaconda3-2022.05.json

Last version that supports Windows 32-bit
See: https://docs.anaconda.com/anaconda/install/old-os/
"Windows 32-bit - Use Anaconda versions 2022.05 and earlier."
I suggest we put a note in the Extras current version after merging this.
Relates to https://github.com/ScoopInstaller/Extras/commit/49118356111cc4a5f08b35c406787910f83c5919

anaconda3-2022.05: Add version 2022.05

---

bucket/snipaste-beta.json

Closes #799 
Referring to [this manifest](https://github.com/ScoopInstaller/Versions/blob/ddc675272ff0dd987dd65c7dd7ba58c5be7c0680/bucket/smplayer-with-smtube.json#L35-L38), `config.ini` is persisted manually by command `Copy-Item`.
And also, `config.ini` is removed from the `persist` block, in case there would be conflict of two implementations of **persist**.

snipaste-beta: Persist config file manually

---

bucket/dotnet6-sdk.json

dotnet6-sdk: Add arm64 architecture

---

bucket/vscode-insiders.json

Incorporated similar method of checkver/autoupdate from VSCode stable manifest from extras bucket (https://github.com/ScoopInstaller/Extras/blob/master/bucket/vscode.json)
Also referenced the VSCode team's release API "docs" at https://update.code.visualstudio.com/swagger.json
This manifest change sets the `version` property according to the published version from the release pipeline, then uses their release API during checkver to set scoop's `$version` variable. 
No changes to the URLs in autoupdate are needed (or possible because the static download URL for insider versions don't follow the same URL scheme as the stable version) since the alias `latest` is always sufficient to redirect to the underlying download location.
Closes #837

vscode-insiders: fix autoupdate/checkver

---

bucket/odin-dev.json

Odin seems to have changed their folder structure again, like pre #742. I'll suggest that the Odin project keeps their folder structure the same in the near future, but this just fixes the latest version.
Relates to #742 
Relates to #740

odin-dev: Remove `extract_dir` to solve `bin` error

---

bucket/php80-xdebug.json
bucket/php81-xdebug.json
bucket/php82-xdebug.json

Add php-xdebug 3.2.0 version for PHP 8.0, 8.1, 8.2

php80-xdebug: Add version 3.2.0

---

bucket/autohotkey1.1.json
bucket/ffmpeg-nightly.json
bucket/ipfilter-nightly.json

Minor: stricter `checkver.regex`
Reason: When `checkver.script` fails due to gh rate limits, it falls back to the default `checkver`
[Example](https://github.com/ScoopInstaller/Versions/commit/d23b52ae7488f563a9307df84b4c84ef77271c1e)
[Example 2](https://github.com/ScoopInstaller/Versions/commit/42cab9c3fa46de8ecf6f16c5383f760662aa84fa)
[Example 3](https://github.com/ScoopInstaller/Versions/commit/0a8f4aea3dd97b563085550df40fb9615b8c0684)

(ipfilter,ffmpeg)-nightly: Add try/catch to `checkver.script`

---

bucket/systeminformer-nightly.json

Fixes this bug that I had with this app while updating it.

systeminformer-nightly: Fix `architecture.extract_dir`, and fixed other small errors

---

bucket/qview-nightly.json

This allows people to add `imageformats` plugins if they so choose
These are common ones, I'm open to adding more on request, but it's better to at least support these as it's a pretty large amount of functionality.
Relates to https://github.com/ScoopInstaller/Extras/pull/10165

qview-nightly: Add possible plugin persists

---

bucket/kdeconnect-nightly.json

- Fixes a change in the artifact url that caused the manifest autoupdate to fail
- Changed checkver to use the jenkins api to retrieve the build number
- Updated manifest to latest build version

kdeconnect-nightly: Fix autoupdate and update version

---

scripts/everything/install-context.reg

Changes the context menu from 'search with Everything' to 'Search with Everything'. This issue also affects the regular `everything` version in the extras bucket. PR for that: https://github.com/ScoopInstaller/Extras/pull/10243

everything-alpha: Fix typo in context menu item

---

bucket/cloudcompare-alpha.json

- technically it's sometimes alpha and sometimes beta, so I'd say we combine them
- stable release is under Scoop Extras: https://github.com/ScoopInstaller/Extras/blob/1027c39d3d724e3dba4440c2adb8b237d84416da/bucket/cloudcompare.json

CloudCompare: Add version 2.13.alpha

---

bucket/winget1.4.json
bucket/winget1.5.json

[winget-preview](https://github.com/ScoopInstaller/Versions/blob/master/bucket/winget-preview.json) is seeing the 1.5 version, so the 1.4 version was not available.

winget1.4: Add version 1.4.10173, winget 1.5: Add version 1.5.101

---

bucket/godot-alpha.json
bucket/godot-beta.json
bucket/godot-mono-beta.json
bucket/godot-mono-rc.json
bucket/godot-rc.json

Fix Godot autoupdate url
Relates to #955

fix: godot url #955

---

bucket/mariadb103.json

- Updated checkver to use their api to find the latest point release: https://mariadb.org/downloads-rest-api/#list-of-files-for-a-latest-release
- Removed 32-bit support as builds stopped after 10.3.32

mariadb103: Update to version 10.3.38

---

bucket/edgedriver-canary.json

Relates to https://github.com/ScoopInstaller/Main/pull/4618
Since the Canary version in the Main bucket has been switched to stable, we should move the Canary version here

edgedriver-canary: Add version 114.0.1782.0

---

bucket/windows-terminal-preview.json

>Note Well, the change from [v1.17.1073](https://github.com/microsoft/terminal/releases/v1.17.10230) where we would munge our version number didn't live much longer than a single release.
The split versioning change from the previous preview was dropped, so checkver is fixed.
>In 1.18 and above: We've removed any runtime dependency on the "desktop" C++ Runtime Library
Removed vcredist suggestion
Converted to portable mode following the stable manifest
https://github.com/microsoft/terminal/releases/tag/v1.18.1421.0
Edit: added settings migration note from extras manifest
Relates to https://github.com/ScoopInstaller/Extras/pull/11335

windows-terminal-preview: Switch to portable distribution

---

bucket/gradle7.json

Add Gradle 7 to versions bucket, seeing that Gradle 8 got released.
Closes [1084](https://github.com/ScoopInstaller/Versions/issues/1084)
- [X ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

Add Gradle 7

---

bucket/ffmpeg-shared-nightly.json

Fix autoupdate for `ffmpeg-shared-nightly` similar to how #796 fixed `ffmpeg-nightly`.

ffmpeg-shared-nightly: Fix checkver and autoupdate

---

bucket/php83.json

Closes #XXXX
-----
<a href="https://stackblitz.com/~/github/suabahasa/versions/tree/master"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/suabahasa/versions/tree/master)._

php: Add version 8.3

---

bucket/bun-canary.json

JavaScript runtime, similar to Node and Deno, designed as a drop-in replacement for Node

bun-canary: Add version 1.0.18-canary.33+61f92d9e5

---

bucket/postman-canary.json

- Update to last version from canary channel: 10.x instead of 9.x (since last stable 9.x is available here as per #665).
- Remove 32bit version (not available more).
- Update links.

postman-canary: Update to version 10.19.15-canary231101-0730

---

bucket/dotnet7-sdk.json

Since .NET 8 is the current version as of November 14th, version 7 should be included in the versions bucket. This might also be a fix for Scoop-managed applications that still use older .NET versions (i.e. `extras/fancontrol`, which also has a .Net 8 version, but the maintainer didn't bother). It would also be a good idea to consider adding a .NET 7 version of `extras/windowsdesktop-runtime` so users don't need the entire SDK, but that's for a different issue.
This manifest has been copied from the last .NET 7 release on main, with a small version bump to 7.0.404
Closes #1483

Added dotnet7-sdk

---

bucket/syncplay-beta.json

Fixes `checkver.script` and `autoupdate.url`
The repo's inconsistent with using `v` in tags, so a case was added for stripping it

syncplay-beta: Update to version 1.7.1-RC1

---

bucket/strawberry-nightly.json

They changed the workflow name/file

strawberry-nightly: Fix `checkver` and `autoupdate`

---

bucket/taiga-beta.json

The reason for this is because inside the `data` dir, `db\anime-relations.txt` (https://github.com/erengy/anime-relations) and `theme` can receive updates relatively often, and `theme` is not very user customizable.
Relates to https://github.com/ScoopInstaller/Extras/pull/11833

taiga-beta: Make `persist` explicit

---

bucket/bun-canary.json

Prevent https://github.com/ScoopInstaller/Versions/issues?q=bun-canary from occuring
NOTE: It is impossible to download GHA artifacts without using GH auth token or the https://nightly.link/ service.

bun-canary: Download from unique artifact url

---

bucket/boost-msvc142.json

add boost for msvc 14.2 so can install for VS 2019 build tools
tested with: scoop install C:\Users\alex\local\ScoopVersions\bucket\boost-msvc142.json

add boost for msvc 14.2 so can install for VS 2019 build tools

---

bucket/dolphin-nightly.json
bucket/filelight-nightly.json
bucket/kate-nightly.json
bucket/kdeconnect-nightly.json
bucket/kdenlive-nightly.json
bucket/labplot-nightly.json
bucket/neochat-nightly.json

Since [migration KDE applications CI from Binary Factory to KDE's GitLab](https://blogs.kde.org/2024/01/30/farewell-binary-factory-add-craft-jobs-your-apps-kdes-gitlab-now/) the following broken manifests updated:
- dolphin-nightly
- filelight-nightly
- kate-nightly
- kdeconnect-nightly
- kdenlive-nightly
- labplot-nightly
- neochat-nightly
TODO (windows builds are not available yet):
- konversation
- okular-nightly
Relates to ScoopInstaller/Extras#12897

kde-apps: Migrate from binary-factory.kde.org

---

bucket/okular-nightly.json

- Migrate from binary-factory.kde.org.
- Update to the latest version.
Relates to #1662

okular-nightly: Update to version 4709

---

bucket/spark33.json

This PR adds the Spark 3.3.x series which is the most recent version available in Cloudera.
If this is desired, it would be easy to add other Spark versions as well.

spark33: Add version 3.3.4

---

bucket/doublecmd-beta.json

doublecmd-beta: Add version 1.1.10

---

bucket/strawberry-nightly.json

```pwsh
Running pre_install script...
Remove-Item:
Line |
4 |  … ySetup-*', 'Uninstall' | ForEach-Object { Remove-Item "$dir\$_.exe" }
|                                              ~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot find path '~\scoop\apps\strawberry-nightly\8820060660\Uninstall.exe' because it does not exist.
```

strawberry-nightly: Fix `pre_install`

---

bucket/rtools40.json
bucket/rtools42.json
bucket/rtools43.json

Move current `main/rtools.json` to `versions/rtools43`

rtools43: Add version 4.3.5958.5975

---

bucket/iperf3.5.json

Last version of iPerf 3 that has a 32bit release.

iperf3.5: Add version 3.5

---

bucket/bottom-nightly.json

I mixed up GH's workflows and commits APIs :P, bottom renamed their default branch from `master` to `main`.

bottom-nightly: Fix checkver branch

---

bucket/hadoop-winutils33.json

The author of the original `hadoop-winutils` is too busy to continue working on it, but there is a [recommended fork](https://github.com/steveloughran/winutils?tab=readme-ov-file#status-go-to-cdarlintwinutils-for-current-artifacts) that provides newer versions at [cdarlint/winutils](https://github.com/cdarlint/winutils).
This PR adds version 3.3 from @cdarlint's fork.
Resolves https://github.com/ScoopInstaller/Extras/issues/3009

hadoop-winutils33: Add version 3.3.5

---

bucket/vlc-nightly-ucrt-llvm.json

**VLC tests LLVM builds for win64.**
For more details : [VLC 4.0 Nightly LLVM vs non-LLVM](https://www.reddit.com/r/VLC/comments/w2i0mr/vlc_40_nightly_llvm_vs_nonllvm/)

vlc-nightly-ucrt-llvm : Add version 20230222

---

bucket/python-alpha.json
bucket/python-beta.json
bucket/python-pre.json
bucket/python-rc.json
bucket/python310.json
bucket/python311.json
bucket/python312.json
bucket/python35.json
bucket/python36.json
bucket/python37.json
bucket/python38.json
bucket/python39.json
bucket/tesseract3.json
bucket/tesseract4.json

```
WARN  "env" will be deprecated. Please change your code/manifest to use "Set-EnvVar"
```
Relates to https://github.com/ScoopInstaller/Main/pull/5849

chore: Replace deprecated `env` function with `(Set|Get)-EnvVar`

---

bucket/chromium-nosync.json

chromium-nosync@125.0.6422.61-r1287751: fix checkver regex not working + remove redundant 32bit version

---

bucket/marknote-nightly.json

Add manifest for nightly builds of Marknote - new WYSIWYG note-taking application from KDE.
Closes #1757

marknote-nightly: Add version 506

---

bucket/less-beta.json

Adds v658 (latest beta) of less binaries for windows.
Closes #1796

less-beta: Add version 658

---

bucket/greenshot-unstable.json

- Update to the latest version.
- Fix `checkver`.
Closes #1590
Closes #1286

greenshot-unstable: Update to version 1.3.277

---

bucket/systeminformer-nightly.json

- Update to version 3.1.24192
- Fix autoupdate to track canary versions.
Closes #1838

systeminformer-nightly: Update to version 3.1.24192

---

bucket/qview-nightly.json

I'm not really sure why this manifest wasn't being updated by actions properly, as running `checkver.ps1` had 0 issues.

qview-nightly: Update to version 9929965521

---

bucket/zed-nightly.json

Adds [Zed](https://zed.dev/) nightly build for Windows. 
There is no official Windows build yet, but it is very usable. So I created a nightly build here: https://github.com/deevus/zed-windows-builds

zed-nightly: add 20240721

---

bucket/nodejs-nightly.json

Relates to https://github.com/ScoopInstaller/Main/pull/6264

nodejs-nightly: Deprecate 32bit & Update to version 24.0.0-nightly202410199f5000e0f2

---

bucket/dbeaver-ea.json
bucket/dbeaver-nightly.json

Add new manifest for DBeaver Early Access. https://dbeaver.io/files/ea/

DBeaver Nightly: Add version 24.3.0-2024-11-20

---

bucket/beyondcompare4.json
scripts/beyondcompare4/install-context-32bit.reg
scripts/beyondcompare4/install-context-64bit.reg
scripts/beyondcompare4/uninstall-context.reg

-'move' beyondcompare v4 manifest from bucket 'extras' to bucket 'version'
- give leeway for Beyond Compare v5 in 'extras'
- see discussion https://github.com/ScoopInstaller/Extras/pull/14026#issuecomment-2575140902
- see discussion https://github.com/ScoopInstaller/Extras/pull/14026#issuecomment-2575237952
- see discussion https://github.com/ScoopInstaller/Extras/pull/14026#issuecomment-2576357032
Relates to https://github.com/ScoopInstaller/Extras/issues/13663
FYI @HUMORCE

beyondcompare4: Add manifest, version 4.4.7.28397

---

bucket/odin-dev.json
bucket/odin-nightly.json
bucket/odin.json

Closes #1778
Odin releases currently have a structure of:
```
odin-windows-amd64-dev-2024-12.zip
| - dist.zip
| - dist
| LICENSE
| base
| core
| examples
| LLVM-C.dll
| odin.exe
| shared
| vendor
```
Adding the `extract_dir` property with a value of `dist` allows Odin to be installed properly.

odin@2024-12: Add extract_dir property to odin and odin-dev

---

bucket/zed-opengl-nightly.json

zed-opengl-nightly: add 03-11-2025

---

bucket/vlc-nightly.json

win32 builds have been deprecated since 2024-02-05 https://github.com/videolan/vlc/commit/8c8f3159718a5d79c9157b574618172cb54e4037
Closes #2065

vlc-nightly: remove win32 build

---

bucket/sqlitebrowser-nightly.json

Closes #2145
Use nightly tag instead of the nightly server, which now includes a partial date version as a segment in the url. Also, the server's stable [latest link](https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win64.zip) hasn't been updated since last December (2023-12-23).
Nightly server old format:
```
version: $year-$month-$day
url: https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-$year-$month-$day-win64.zip
```
Nightly server new format:
```
version: $year-$month-$day
url: https://nightlies.sqlitebrowser.org/win64/$year-$month/DB.Browser.for.SQLite-$year-$month-$day-win64.zip
```

sqlitebrowser-nightly: Use github releases and update to 20250118 (#2145)

---

bucket/php83-xdebug.json

✨ Added `php83-xdebug` manifest #1957

---

bucket/gimp-dev.json

Allows the CI/CD pipeline to pick up GIMP v3 release candidates. Resolves #2088

gimp-dev v3.0.0-RCx

---

bucket/cherry-studio-pre.json

Closes #2197 
Simply clone the Extras/cherry-studio manifest and modify the checkver part.

cherry-studio-pre: add version 1.1.4

---

bucket/thorium-avx2.json

A version of the package I have submitted for Scoop/Extras, this version of thorium is compiled for CPUs that have AVX2 support

Thorium-AVX2: add version 117.0.5938.157

---

bucket/windowsdesktop-runtime-7.0.json

Now that v8 is both the regular and LTS version, it seems fitting to add v7 here — especially since some apps are built for this specific version and nothing else.

windowsdesktop-runtime-7.0: Add version 7.0.20

---

bucket/wox-beta.json

The goal of this PR is to update the Wox package to the [v2.0.0-beta.2](https://github.com/Wox-launcher/Wox/releases/tag/v2.0.0-beta.2) beta.
It seems that the versioning scheme has changed (no idea if it's permanent or temporary for this dev cycle).
Package has been installed successfully via local testing.
If this repo intends to stick to the currently available [v1.4.1196](https://github.com/Wox-launcher/Wox/releases/tag/v1.4.1196) pre-release feel free to close the PR.
Closes NONE
Relates to NONE

Update wox-beta to version 2.0.0-beta.2 with new installer script

---

bucket/windowsdesktop-runtime-6.0.json
bucket/windowsdesktop-runtime-7.0.json

This PR makes the following changes:
- `windowsdesktop-runtime-6.0`: Update to version `6.0.36`, update checkver.
- `windowsdesktop-runtime-7.0`: Update checkver.
Closes #2301

windowsdesktop-runtime-6.0(7.0): Update checkver

---

bucket/googlechrome-canary.json

Reference: https://scoop.sh/UpdateTracker/googlechrome/chrome.min.xml (content update: ScoopInstaller/UpdateTracker@f7bbf67ac8d543a717d4f16f8d2b11deb3baa716)
Add _uncompressed before .exe to URL.  
As the installer is not compressed, we can get Chrome-bin directly from dl.7z .  
So the install process is just to copy files inside Chrome-bin to $dir.
Affected since: 139.0.7247.0
Closes #2351

googlechrome-canary: Fix download URL

---

bucket/llama.cpp-cu124.json

llama.cpp-cu124: Fix the autoupdate url

---

bucket/7zip-zstd.json

Added missing 7zFM.exe shim for 7z-zstd
Closes #2391

7zip-zstd@v24.09-v1.5.7-R1: add `7zFM.exe` to  `bin`

---

bucket/systeminformer-nightly.json

- The 3 versions of `systeminformer-nightly` released in the last 24 hours use the filename `systeminformer-build-bin.zip` instead of `systeminformer-$version-bin.zip`. Changed the manifest to fix this.
- Changed `checkver` to use GitHub instead of SourceForge. Since GitHub now provides hashes for their release assets I don't see a point in using SourceForge for getting the hashes.
Output of `checkurls.ps1` and `checkver.ps1` for the updated manifest:
<details><summary>checkurls.ps1</summary>
```console
❯ ..\bin\checkurls.ps1 systeminformer-nightly
[U]RLs
| [O]kay
|  | [F]ailed
|  |  |
[1][1][0] systeminformer-nightly
```
</details>
<details><summary>checkver.ps1</summary>
```console
❯ $env:SCOOP_DEBUG = 'true'; ..\bin\checkver.ps1 systeminformer-nightly -Force
systeminformer-nightly: …
```

systeminformer-nightly: Update to version 3.2.25263.236, fix checkver & autoupdate

---

bucket/ols-nightly.json

> Added `ols-nightly` package to provide Odin Language Server
Title is self explanatory.
Added an `ols-nightly` package which access to nightly builds for the [DanielGavin/ols](https://github.com/DanielGavin/ols) tool.
I would have provided a `ols-dev` and `ols` package but the main releases do not appear to have artifacts attached. I am looking into adding those into the aforementioned repository via a pull request.

ols-nightly: Add version 20250928-g4a2a71e
