php55.json

Update PHP 5.5.31 to PHP 5.5.32

Update to PHP 5.5.32

---

php56.json

Update to PHP 5.6.20 from PHP 5.6.18

Update to PHP 5.6.20

---

apache24.json
nodejs010.json
nodejs012.json
nodejs4.json
openssl10x.json
php56.json
php70.json

Changes based on https://github.com/lukesampson/scoop/pull/1432

Remove unnecessary type, mode, find definitions and fix some hashs

---

php54.json
php55.json
php56.json
php70.json

I tested them all (64-bit only)

Add suggests to php*

---

tomcat6.json
tomcat7.json
tomcat80.json

Use same autoupdate as in extras

---

tomcat7.json
tomcat80.json

@r15ch13 Sorry, not my day today. I thought I ran `bin\checkver.ps1 -u -f tomcat*.json` but obviously I didn't. I owe you a beer.

Update version in URL

---

apache24.json
nodejs010.json
nodejs012.json
nodejs4.json
nodejs6.json
nodejs7.json
nodejs8.json
nodejs9.json
php55-xdebug.json
php56-xdebug.json
php70-xdebug.json
php71-xdebug.json
python35.json
ruby19.json
tesseract4.json

Untested, so please review carefully.

Add quotes around $dir/$persist_dir vars

---

Scoop-Bucket.Tests.ps1

lukesampson/scoop#2024 moved some DLLs and I guess it will break those tests.
See also lukesampson/scoop#2034
Best regards,
Philippe Crama

Adapt to path change of validator dlls from lukesampson/scoop#2024

---

springboot15.json

Follow-up for https://github.com/lukesampson/scoop-extras/pull/903

springboot 1.5 support

---

tomcat6.json
tomcat7.json
tomcat80.json
tomcat85.json

See scoop issue [#2622](https://github.com/lukesampson/scoop/issues/2622).

Remove/update suggests for oraclejre/-server

---

pwsh-prev.json

Add powershell core preview version

Add pwsh-prev

---

anaconda2.json

lukesampson/scoop-extras#1552
I think this maybe could be mainly a `alternative` version to `anaconda3`, so should be pushed here.

Add Anaconda2

---

bucket/anaconda2.json
bucket/miniconda2.json

- anaconda2: modify
- add `python.exe` to bin
- fix `url`, `installer` and `uninstaller`
- add `persist`
- mod `autoupdate`
- miniconda2: add 4.5.12

conda: Fix anaconda2 and add miniconda2

---

bucket/postgresql10.json

- Update to version 10.6
- Fix `checkver`

postgresql10: Fix checkver

---

bucket/rclone-beta.json

- Fix manifest and be consist with rclone (https://github.com/lukesampson/scoop/pull/3108)

rclone-beta: Fix manifest

---

bucket/premake4.json
bucket/premake5.json

Fix manifests of premake4 and premake5

premake: Modify premake4 and premake5

---

bucket/vivaldi-beta.json

Close https://github.com/lukesampson/scoop-extras/issues/1799

vivaldi-beta: Add version 2.4.1476.4

---

bucket/sts396.json

Copy from extras/sts, latest 32bit version of Spring Tool Suite

sts396: Add latest 32bit version of sts

---

bucket/atom-portable.json

Atom (stable release) portable version.

Add atom-portable

---

bucket/lamexp-qaac.json

Ref: https://github.com/lukesampson/scoop-extras/pull/1911

LameXP: Add QAAC version

---

bucket/tesseract3-languages.json
bucket/tesseract3.json
bucket/tesseract4-languages.json
bucket/tesseract4.json

tesseract: Fix according to https://github.com/lukesampson/scoop/blob/17b0f221dcc08abf5e87141c58a1a80466081e53/bucket/tesseract.json
tesseract-languages: Add tesseract3-languages and tesseract4-languages

tesseract: Fix tesseract3/4 and add tesseract3/4-languages

---

bucket/wget120.json

Version 1.20.3 has issues. See https://github.com/lukesampson/scoop/issues/3331 and https://eternallybored.org/misc/wget/

Add wget120: wget 1.20

---

bucket/tesseract3-languages.json
bucket/tesseract4-languages.json

ref: https://github.com/scoopinstaller/scoop-main/pull/7

tesseract-languages: Fix urls

---

bucket/nodejs010.json
bucket/nodejs012.json
bucket/nodejs10.json
bucket/nodejs11.json
bucket/nodejs12.json
bucket/nodejs4.json
bucket/nodejs5.json
bucket/nodejs6.json
bucket/nodejs7.json
bucket/nodejs8.json
bucket/nodejs9.json

Node.js: Add v5, v10, v11, v12, patch existent ones.

---

bucket/dotnet-sdk-lts.json
bucket/dotnet-sdk-preview.json

.Net Core SDK: Add LTS and Preview versions

---

bucket/dotnet-sdk-lts.json
bucket/dotnet-sdk-preview.json

Ref: https://github.com/ScoopInstaller/Main/pull/153

dotnet-sdk: Fix 'env_set'

---

bucket/orca3.json

orca: Add version 3.1.4000.1830

---

bucket/pwsh-beta.json

it's located in root dir of pwsh-beta

pwsh-beta: persist `$profile.allusersallhosts`

---

bucket/php56.json
bucket/php70.json

Addresses https://github.com/ScoopInstaller/Versions/issues/21#issuecomment-500088862

php56, php70: Remove autoupdate and fix URL

---

bucket/haskell863.json

haskell: Add 32bit (v8.6.3)

---

bucket/terraform011.json

\>0.11 have breaking API changes.

Add terraform 0.11

---

bucket/edgedriver-legacy.json

Move legacy MicrosoftEdgeDriver here.

edgedriver-legacy: Add version 6.17134

---

bucket/neovim-nightly.json

Node.js is licensed under MIT.

neovim-nightly: Remove checkver and autoupdate

---

bucket/fmedia16.json

fmedia: Add version 1.6

---

bucket/php73.json

php73: Fix hashes

---

bucket/openssl-light.json
bucket/openssl10-light.json
bucket/openssl10.json

openssl: Add Light version and change 'openssl10' to full version

---

bucket/snipaste-beta.json

Fix https://github.com/lukesampson/scoop-extras/issues/2472

snipaste-beta: Fix checkver and au.hash

---

bucket/gitea-beta.json

Ref: https://github.com/lukesampson/scoop-extras/pull/2460

gitea-beta: Add version 1.9.0-rc2

---

bucket/xmplay-stuff.json

Add XMPlay 3.8.3.20 (Stuff Version)

---

bucket/graphicsmagick-q16.json

See https://github.com/ScoopInstaller/Main/issues/357

Move main/graphicsmagick-q16 to versions bucket

---

bucket/python37.json

This version was missing after the main bucket was updated to use v3.8

python: Add version 3.7.x

---

bucket/haskell863.json

Ref: https://github.com/ScoopInstaller/Main/pull/639

haskell863: Remove 'stack.exe' bin

---

bucket/7zip-beta.json

Per https://github.com/ScoopInstaller/Main/issues/773 and https://repology.org/repository/scoop/problems

7zip-beta: Fix homepage URL

---

bucket/mysql56.json
bucket/mysql57.json

mysql5x: Update manifests

---

bucket/gogs0.json

gogs0: Add last 32bit version

---

bucket/rstudio-daily.json

refs
https://github.com/lukesampson/scoop-extras/pull/3510

added rstudio daily

---

bucket/php54-xdebug.json
bucket/php55-xdebug.json
bucket/php56-xdebug.json
bucket/php70-xdebug.json
bucket/php71-xdebug.json
bucket/php72-xdebug.json
bucket/php73-xdebug.json
bucket/php74-xdebug.json
bucket/php74.json

php-xdebug: Add version 2.4.1-5.4 and improve checkver

---

imagemagick-ffmpeg.json

Per https://github.com/ScoopInstaller/Main/pull/1394#issuecomment-691789918
Closes https://github.com/ScoopInstaller/Main/pull/1394

imagemagick-ffmpeg: Add alt version of imagemagick

---

bucket/rclone-beta.json

rclone-beta: Fix checkver

---

bucket/perl-pdl.json

Fix checkver to reflect ScoopInstaller/Main#966

perl-pdl: Update to version 5.32.0.1

---

bucket/nodejs010.json
bucket/nodejs012.json
bucket/nodejs10.json
bucket/nodejs11.json
bucket/nodejs12.json
bucket/nodejs4.json
bucket/nodejs5.json
bucket/nodejs6.json
bucket/nodejs7.json
bucket/nodejs8.json
bucket/nodejs9.json

Same as this [PR](https://github.com/ScoopInstaller/Main/pull/1536)

reorder env_add_path for nodejs

---

bucket/go114.json

This PR adds version 1.14 of golang.

Add go 1.14 manifest

---

bucket/tomcat6.json
bucket/tomcat7.json
bucket/tomcat8.json
bucket/tomcat9.json

* Closes #283 #68 #290
* Related: lukesampson/scoop-extras#5990

tomcat: Add tomcat9 & persist & fixes download url

---

bucket/tomcat9.json

Update Tomcat 9 from version 9.0.45 to 9.0.54

tomcat9: Update to version 9.0.54

---

bucket/nodejs16.json

Added manifest for Node.js version 16

nodejs16: Add version 16.13.0

---

bucket/rtools35.json

rtools35: Add version 3.5.0.4

---

bucket/whatsapp-beta.json

Co-authored-by: Alcazer Barış TÜRKGÜCÜ <code@alcazer.com>

whatsapp-beta: Add version 2.2144.2

---

bucket/rstudio11.json

Ref: https://github.com/lukesampson/scoop-extras/pull/3366

rstudio11: Add version 1.1.463

---

bucket/lua-joedf.json

lua-joedf: Add version 5.4.3

---

bucket/lua53.json

For https://github.com/ScoopInstaller/Main/pull/2929

lua53: Add version 5.3.6

---

bin/checkurls.ps1
bin/formatjson.ps1

feat(bin): Add `checkurls` and `formatjson`

---

bucket/openssh-msys.json

Ref: https://github.com/ScoopInstaller/Main/pull/2921#issuecomment-971634048
Closes ScoopInstaller/Main#2921

openssh-msys: Move from `Main`

---

bucket/docker-nightly.json
bucket/ffmpeg-nightly.json
bucket/ffmpeg-shared-nightly.json
bucket/glslang-nightly.json
bucket/neovim-nightly.json
bucket/vim-nightly.json
bucket/vim-tux.json

- vim-nightly: Bump to 8.2.3614 and add 32bit
- vim-tux: Add 8.2.3608

chore: Move nightly manifests from `Main`

---

bucket/wezterm-nightly.json

Closes ScoopInstaller/Extras#7285

wezterm-nightly: Add manifest

---

bucket/linqpad5.json

linqpad5: Add version 5.44.02

---

bucket/brave-beta.json
bucket/brave-nightly.json

Supersedes https://github.com/ScoopInstaller/Extras/pull/2746

brave: Add beta and nightly releases

---

bucket/ruby27.json

I'm not sure if I'm doing it right. I haven't tested this file, I'm not sure how. But if this is something that's wanted I can spend more time on this.

ruby27: Add version 2.7.4-1

---

bucket/bandizip6.json

close #299.
Modified from @HUMORCE's manifest.

bandizip6: Add version 6.29

---

bucket/geogebra5.json

Adding the old/classic version of GeoGebra. Closes request #275

Add GeoGebra 5

---

bucket/aria2-134.json
bucket/aria2-1340.json

aria2-1.34 LAST version with SSLv3.0 and TLSv1.0 support

aria2-134: Add last version with SSLv3.0 and TLSv1.0 support.

---

bucket/dotnet-sdk-lts.json

close https://github.com/ScoopInstaller/Versions/issues/325

dotnet-sdk-lts: env. var. 'MSBuildSDKsPath'

---

bucket/postgresql11.json

hi,
I've added a file for postgresql 11.
The file is taken from https://github.com/ScoopInstaller/Main/blob/master/bucket/postgresql.json but adapted to use version 11

postgresql11: add version 11.14

---

bucket/okular-nightly.json

Closes #254
Based on https://github.com/ScoopInstaller/Extras/blob/master/bucket/okular.json

Add Okular Nightly

---

.github/workflows/issue.yml
.github/workflows/issue_comment.yml
.github/workflows/pull_request.yml

See https://github.com/ScoopInstaller/Extras/pull/7465

chore(ci): Use Windows Actions to avoid SSL errors

---

bucket/neochat-nightly.json

Relates to https://github.com/ScoopInstaller/Extras/issues/7283
Closes https://github.com/ScoopInstaller/Nightlies/issues/6

NeoChat Nightly: Add version 346

---

bucket/ruffle-nightly.json

Hi, I thought this program would be a good fit for the Versions bucket since there's no stable release yet. It has a CLI with options but it can also be run from the start menu where it prompts to select a file to open using default settings. Quite popular too - about 9k stars.

ruffle-nightly: Add version 2021-12-09

---

bucket/postgresql12.json

This is as https://github.com/ScoopInstaller/Versions/pull/327 but for version 12

postgresql: add version 12.09

---

bucket/postgresql13.json

This is as #327 but for version 13

postgresql: add version 13.05

---

bucket/xournalpp-nightly.json

- Moved from lukesampson/scoop-extras#5195
- Closes lukesampson/scoop-extras#4670

xournalpp-nightly: Add version 1.1.0-20201124

---

bucket/ffmpeg-gyan-nightly.json

Closes #350 
Let me know if I should only use the date for the version

ffmpeg-gyan-nightly: Add version 2021-12-23

---

bucket/vlc-nightly.json

- Closes #284
- Based on https://github.com/ScoopInstaller/Extras/blob/master/bucket/vlc.json
- Using a similar technique to checkver in https://github.com/ScoopInstaller/Extras/pull/7586
- ~Caveat: extract_dir will need to be updated once the nightly moves from 4.0 to 4.1/5.0 etc.~ Fixed in second commit

Add vlc-nightly

---

bucket/ruby19.json

[Bintray has been closed](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

ruby19: update URLs

---

bucket/everything-beta.json

I know that at the moment, it's the same as the version in `extras`, but this will change when there's a new beta out.

everything-beta: Add version 1.4.1.1002

---

bucket/everything-alpha.json

Stable version has been updated to 1.4.
Closes #252

everything-alpha: Add version 1.5.0.1290a

---

bucket/python27-beta.json
bucket/python27.json
bucket/python38-beta.json
bucket/python39-beta.json

python-beta: Add python38-beta and python39-beta

---

bucket/micro-nightly.json

- Closes #217
- Based on manifest in Main

micro-nightly: add version 2.0.11-dev.38

---

bucket/snipaste-beta.json

snipaste-beta: Update to version 2.7.1-Beta

---

bucket/scala212.json

Hi @tech189 , @sualeh,
Redoing the PR from branch adambridge-scala as suggested. Checkver should work correctly now as well.
(Continued from https://github.com/ScoopInstaller/Versions/pull/265)

Add Scala 2.12.x

---

bucket/vlc-nightly.json

Closes #XXXX
Relates to https://github.com/ScoopInstaller/GithubActions/issues/3

vlc-nightly: Change checkver conflicted variable

---

bucket/gimp-dev.json

Relates to https://github.com/ScoopInstaller/Extras/pull/7650

Change conflicting version variable in gimp-dev

---

bucket/everything-alpha.json

everything-alpha: Add Everything64.exe fix

---

bucket/ffmpeg-nightly.json
bucket/ffmpeg-shared-nightly.json

ffmpeg-nightly, ffmpeg-shared-nightly: Update to version 105057 and fix checkver

---

bucket/chromium-nosync.json

…pdate
Closes #XXXX
Relates to https://github.com/ScoopInstaller/Extras/issues/7292 and https://github.com/ScoopInstaller/Extras/pull/7665
- List of files can be found here: : https://github.com/LazyGeniusMan/Sc00p-Test/runs/4697442253?check_suite_focus=true#step:3:115

chromium-nosync: Add version 96.0.4664.93-r929512

---

bucket/chromium-dev-nosync.json

Closes #XXXX
Relates to https://github.com/ScoopInstaller/Extras/issues/7292
- List of files : https://github.com/LazyGeniusMan/Sc00p-Test/runs/4697969285?check_suite_focus=true#step:3:11
- I tried using regex for hash but it's not working:  https://github.com/LazyGeniusMan/Sc00p-Test/commit/41342bbf4b98707d52b6c0dd254fd6bdfa743c50

chromium-dev-nosync: Update to version 99.0.4800.0-r954746 and add autoupdate

---

bucket/chromium-dev.json

Closes #XXXX
Relates to https://github.com/ScoopInstaller/Extras/issues/7292
- List of files can be found here: https://github.com/LazyGeniusMan/Sc00p-Test/runs/4697721304?check_suite_focus=true#step:3:10
- Should I also add bin & scripts that's used in ungoogled-chromium ?

chromium-dev: Update to version 99.0.4806.0-r955034 and fix autoupdate

---

bucket/neovim-bare-nightly.json
bucket/neovim-bare.json

These manifests decouple Neovim from the heavily outdated [neovim-qt](https://github.com/equalsraf/neovim-qt) GUI client.

neovim-bare(-nightly): Add manifests

---

bucket/tdm-gcc.json

tdm-gcc: add version 10.3.0

---

bucket/imagemagick-ffmpeg.json

Fixes issue in autoupdate here: https://github.com/ScoopInstaller/Versions/runs/4707066592?check_suite_focus=true#step:3:194

Fix imagemagick-ffmpeg autoupdate

---

bucket/gn.json

GN is a meta-build system that generates build files for Ninja.

gn: Add version 9PAEvy

---

bucket/kodi-nightly.json

- Based on my PR of the stable version: https://github.com/ScoopInstaller/Extras/pull/7756
- Uses installer script similar to my vlc-nightly and inkscape scripts! 😄
- I will also make a PR for the Dev version (20.x atm) in the near future

kodi-nightly: add version 20220117

---

bucket/joplin-pre.json

joplin-pre: Added version 2.7.7 (pre-release)

---

bucket/kodi-dev.json

- Relates to #393
- Almost the same as kodi-nightly manifest, just slightly different url

kodi-dev: add version 20220118

---

bucket/rambox-ce.json

Relates to https://github.com/ScoopInstaller/Extras/pull/7780

rambox-ce: Add version 0.7.9

---

bucket/winpython37.json
bucket/winpython3741.json
bucket/winpython37cod.json
bucket/winpython37ps2.json
bucket/winpython38.json
bucket/winpython38cod.json
bucket/winpython38ps2.json

- winpython37: Python 3.7 (w/PyQT5)
- winpython37ps2: Python 3.7 with PySide2 (w/o PyQT5)
- winpython37cod: Python 3.7 with VSCode (w/ PyQT5)
- winpython38: Python 3.8 (w/PyQT5)
- winpython38ps2: Python 3.8 with PySide2 (w/o PyQT5)
- winpython38cod: Python 3.8 with VSCode (w/ PyQT5)
- winpython3741: Python 3.7.4.1 (latest 32bit full dist)

winpython: Add various versions

---

bucket/influxdb1.json

Since InfluxDB has change its main version to 2.x, move 1.x from 'Main' to here.

influxdb1: Move from 'main' bucket

---

bucket/fluxctl.json

Relates to https://github.com/ScoopInstaller/Versions/pull/401#issuecomment-1019313849

fluxctl: Move from 'Main' bucket

---

bucket/firefox-beta.json
bucket/firefox-developer.json
bucket/firefox-nightly.json

consistent with extras bucket: https://github.com/ScoopInstaller/Extras/pull/7843

firefox-(beta|developer|nightly): Update manifest

---

bucket/pijul.json

Pijul is a free and open source (GPL2) distributed version control system. Its distinctive feature is to be based on a theory of patches, while still being fast and scalable. This makes it easy to learn and use, without any compromise on power or features.

Pijul: Add version 1.0.0-beta

---

bucket/vim-nightly.json
bucket/vim-tux.json
scripts/vim/install-context.reg
scripts/vim/uninstall-context.reg

Relates to https://github.com/ScoopInstaller/Main/pull/3291

vim-(tux|nightly): Do not copy example config files

---

bucket/firefox-beta.json
bucket/firefox-developer.json
bucket/firefox-nightly.json

consistent with https://github.com/ScoopInstaller/Extras/pull/8017

firefox-*: Allow appending of additional items

---

bucket/micaforeveryone-dev.json

Relates to https://github.com/ScoopInstaller/Extras/pull/8008

micaforeveryone-dev: Add version 0.1.0.4-rc1

---

bucket/vim-nightly.json
bucket/vim-tux.json

Relates to https://github.com/ScoopInstaller/Scoop/pull/4722

vim-*: Fix 'current_dir' error

---

bucket/imageglass-moon.json

- Relates to https://github.com/ScoopInstaller/Extras/pull/8140 - while working on this I noticed there is a beta/development build for ImageGlass which is not in Versions, so I made this PR!
- It is mostly based on the Extras `imageglass` manifest, with my fixes from the PR linked above.

imageglass-moon: add version 8.5.2.15

---

bucket/processhacker-nightly.json

processhacker-nightly: Add persist

---

bucket/python27-beta.json
bucket/python27.json

Add EOL notice to Python 2 manifests

---

bucket/processhacker-nightly.json

Fixes https://github.com/processhacker/processhacker/issues/884

processhacker-nightly: Delete icon guids in `post_install`

---

bucket/git-without-openssh.json

See https://github.com/git-for-windows/git/discussions/3451
Relates to ScoopInstaller/Main#3438

git-without-openssh: Add version 2.35.1

---

bucket/processhacker-nightly.json

Fixes #469, Closes #470
Do not continue if the `settings` node does not exist.

processhacker-nightly: Fix post_install failure

---

bucket/php72.json
bucket/php73.json

Changes:
- Fix url path for PHP 7.2 & PHP 7.3 versions
- Remove checkver
- Remove autoupdate

php-7.*: Fix url path

---

bucket/posh-git-beta.json
bucket/posh-git-nightly.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scoopinstaller/versions/187)

posh-git: Add beta version 1.1.0 & nightly version cb070b7773

---

bucket/goneovim-nightly.json

goneovim: Add version nightly

---

bucket/ferdium-nightly.json

ferdium-nightly: Add version 6.0.0-nightly.7

---

bucket/r41.json
bucket/rtools35.json
bucket/rtools40.json

Relates to https://github.com/ScoopInstaller/Main/pull/3530#issuecomment-1113449128

R|RTools: Move version 4.1|4.0 from Main

---

bucket/kicad-lite-nightly.json

Relates to #258. Renamed to keep `-nightly` at the end of an app's name. Added a Last Modified check to checkver, which should catch when the latest version is updated but not increased in version number.

kicad-lite-nightly: Add latest version

---

bucket/idea-ultimate-eap.json

IntelliJ IDEA Ultimate EAP: Update to version 222.2270.31

---

bucket/godot-alpha.json
bucket/godot4.json

Add Godot 4 Alpha 8

---

bucket/sumatrapdf-install.json
bucket/sumatrapdf-installer.json

Sumatra install version with thumbnail support

---

bucket/freecad-weekly.json

Relates to Excavator unable to update: https://github.com/ScoopInstaller/Versions/runs/6789965591?check_suite_focus=true#step:3:223

freecad-weekly: Update to v. 29045, fix autoupdate

---

bucket/lua51.json

lua51: make shims consistent

---

bucket/windows-terminal-preview.json
scripts/windows-terminal-preview/install-context.reg
scripts/windows-terminal-preview/uninstall-context.reg

Closes https://github.com/ScoopInstaller/Extras/issues/4831
Relates to #224

windows-terminal-preview: Add version 1.14.1451.0

---

bucket/sqlitebrowser-nightly.json

sqlitebrowser-nightly: Add 16-Jun-2022

---

bucket/olive-editor-nightly.json

Another attempt to add Olive Editor Nightly. 
This uses nightly.link as a proxy service for Github Actions artifacts
Relates to #342

olive-editor-nightly: Add manifest

---

bucket/stash-dev.json

stash-dev: add version 0.15.0-33-g813495c7

---

bucket/kotatogram-beta.json

kotatogram-beta: add version 1.4.9

---

bucket/omnisharp-http-net6.json
bucket/omnisharp-net6.json

Omnisharp: Add net6 variant for version 1.39.0

---

bucket/github-beta.json

- Closes #574 
- Based on [Extras/github](https://github.com/ScoopInstaller/Extras/blob/master/bucket/github.json) (GitHub Desktop stable)

github-beta: Add version 3.0.3-beta1

---

bucket/everything-beta.json

everything-beta: fix unexpected trailing comma error 

---

bucket/caret-beta.json

* follow up of https://github.com/ScoopInstaller/Extras/pull/8885

caret-beta: Add version 4.0.0-rc23

---

bucket/ds4windows-circumspector-pre.json

Main [fork](https://github.com/CircumSpector/DS4Windows) of [Ryochan7's DS4Windows](https://github.com/Ryochan7/DS4Windows) when it was archived.

ds4windows-circumspector-pre: Add version 3.1.908

---

bucket/mingw-winlibs-llvm.json

Updated version and fixed autoaupdate issue

mingw-winlibs-llvm: Update to version 12.1.0-14.0.4-10.0.0-r2

---

bucket/inkscape-dev.json

- Development version of Inkscape (currently on 1.3 branch vs. stable 1.2): https://inkscape.org/release/inkscape-dev/
- Custom checkver script similar to `kodi-nightly`
- Nothing to persist, just like stable Inkscape, all settings in `AppData\Roaming\inkscape`

inkscape-dev: Add version 1.3-dev_2022-07-24

---

bucket/zip-beta.json

[Info-ZIP](https://spdx.org/licenses/Info-ZIP.html) has its own entry in the SPDX. In line with https://github.com/ScoopInstaller/Main/pull/3809.

chore: Update Info-ZIP licenses

---

bucket/xampp74.json

xampp74: Add version 7.4.29-1

---

bucket/obs-studio-pre.json

obs-studio-pre: Add version 28.0.0-rc1

---

bucket/julia-lts.json
bucket/julia-rc.json

julia: Add RC and LTS version

---

bucket/kate-nightly.json

Relates to [Extras/#9307](https://github.com/ScoopInstaller/Extras/pull/9307)
Based on [okular-nightly.json](https://github.com/ScoopInstaller/Versions/blob/master/bucket/okular-nightly.json)

kate-nightly: Add version 1705

---

bucket/prusaslicer-pre.json

`prusaslicer-pre` includes alpha/beta/rc releases in [PrusaSlicer GitHub releases page](https://github.com/prusa3d/PrusaSlicer/releases)

prusaslicer-pre: Add version 2.5.0-rc2

---

bucket/php74.json

php74: Fix URLs and update Hashes.

---

bucket/spotdl-beta.json

spotdl-beta: Add version 4.0.0-rc.3

---

bucket/qview-nightly.json

[It's in extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/qview.json)

qview-nightly: Add version 1088

---

bucket/php80.json

php80: Update to version 8.0.24

---

bucket/strawberry-nightly.json

[It's in extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/strawberry.json)

strawberry-nightly: Add version 3116133961

---

bucket/taiga-beta.json

[It's in extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/taiga.json)

taiga-beta: Add version 1.4.0-beta.2

---

bucket/mpv.net-beta.json

[It's in extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/mpv.net.json)

mpv.net-beta: Add version 6.0.3.1

---

bucket/wireshark3.6.json

This is the last version of the official 32-bit Windows packages for Wireshark.
Details: <https://www.wireshark.org/docs/relnotes/wireshark-4.0.0.html>

wireshark3.6: Add version 3.6.8

---

bucket/spotify-qt-nightly.json

Relates to https://github.com/ScoopInstaller/Extras/pull/9338

spotify-qt-nightly: Add version 3.9-221005

---

bucket/freac-continuous.json

[It's in extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/freac.json)

freac-continuous: Add version 3207336453

---

bucket/godot-beta.json

godot-beta: Add version 4.0-beta1

---

bucket/bottom-nightly.json

[It's in main](https://github.com/ScoopInstaller/Main/blob/master/bucket/bottom.json)

bottom-nightly: Add version 3212308515

---

bucket/syncplay-beta.json
syncplay-beta.json

[It's in extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/syncplay.json)

syncplay-beta: Add version 1.7.0-Beta1

---

bucket/wireshark3.json

Relates to https://github.com/ScoopInstaller/Extras/issues/9468

wireshark3: Add version 3.6.8

---

bucket/handbrake-cli-snapshot.json
bucket/handbrake-snapshot.json

Created snapshot versions of handbrake and handbrake-cli

---

bucket/python-beta.json
bucket/python310-beta.json
bucket/python39-beta.json

- Relates to https://github.com/ScoopInstaller/Versions/discussions/727

python-beta: Add version 3.12.0a1

---

bucket/tachidesk-server-preview.json
scripts/tachidesk-server-preview/tachidesk-debug.ps1
scripts/tachidesk-server-preview/tachidesk-electron.ps1
scripts/tachidesk-server-preview/tachidesk.ps1

preview version of tachidesk-server

tachidesk-server-preview: Add version 0.6.5-r1136

---

bucket/duplicati-canary.json

duplicati-canary: Add version 2.0.6.104_canary_2022-06-15

---

bucket/odin-dev.json

odin-dev: Add `extract_dir` to solve `bin` error

---

bucket/php74.json

php74: Fix URLs and update hashes

---

bucket/oracle-instant-client-odbc19.json
bucket/oracle-instant-client-sdk19.json
bucket/oracle-instant-client19.json

Add version 19 of Oracle Instant Client and its ODBC/SDK.

oracle-instant-client19: Add version 19.16.0.0.0

---

bucket/nodejs18.json

Closes #754 
- [x ] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

nodejs18: Add version 18.12.1

---

bucket/godot-mono-beta.json

godot-mono-beta: Add version 4.0-beta4

---

bucket/python311.json

python311: Add version 3.11.0

---

bucket/gimp-dev.json

gimp-dev: Fix `hash`

---

bucket/godot-alpha.json
bucket/godot-beta.json

godot-beta & godot-alpha: Fix `pre_install` script

---

bucket/godot-mono-beta.json

godot-mono-beta: Fix and Enhance `pre_install` script

---

bucket/qview-nightly.json

I honestly didn't know this existed when I first opened the pr 😅

qview-nightly: iwr -> irm

---

bucket/handbrake-snapshot.json

handbrake-snapshot: Fix `hash`

---

bucket/kde-dolphin-nightly.json

Relates to https://github.com/ScoopInstaller/Extras/issues/9801

kde-dolphin-nightly: Add version 814

---

bucket/okular-nightly.json

okular-nightly: fix incorrect link

---

bucket/systeminformer-nightly.json

Process Hacker has been renamed to System Informer

systeminformer-nightly: Add version 3.0.5527

---

bucket/postgresql14.json

Add version 14 of `postgresql`
Closes #812

postgresql: Add version 14.6

---

bucket/php82.json

php82: Add version 8.2.0

---

bucket/qview-nightly.json

qview-nightly: Fix extraction

---

bucket/lite-xl-addons.json

Lite XL with addons
> Addons vs non-addons packages
> The addon packages besides including the Lite XL binary also include additional plugins to make the initial experience more accesible. The extra features the addon packages include are:
>
> - All language plugins.
> - All color scheme plugins.
> - Widgets + settings gui plugin for easier configuration.
> - Open externally plugin, which detects if a file been open is valid utf-8 and offers to open it externally if not.

lite-xl-addons: Add version 2.1.0

---

bucket/autohotkey1.1.json

autohotkey1.1: Add version 1.1.36.02

---

bucket/sharex-dev.json

Closes https://github.com/ScoopInstaller/Extras/issues/10073

sharex-dev: Add version 14.1.4.9

---

bucket/labplot-nightly.json

Relates to https://github.com/ScoopInstaller/Extras/issues/6845

labplot-nightly: Add version 1354

---

bucket/everything-alpha.json

everything-alpha: Fix persistent data

---

bucket/kotatogram-beta.json
scripts/telegram/protocol-handler.ps1

Relates to https://github.com/ScoopInstaller/Extras/issues/9244

kotatogram-beta: Added url protocol install process

---

bucket/prismlauncher-git.json
bucket/prismlauncher-qt5-git.json
scripts/prismlauncher-git/install-associations.reg
scripts/prismlauncher-git/uninstall-associations.reg
scripts/prismlauncher-qt5-git/install-associations.reg
scripts/prismlauncher-qt5-git/uninstall-associations.reg

this adds development versions of the prismlauncher packages already present in the [games](https://github.com/Calinou/scoop-games/pull/723) bucket

prismlauncher-git/prismlauncher-qt5-git: add version 7.0-8da6667

---

bucket/sharex-dev.json

sharex-dev: Fix url

---

bucket/godot-rc.json

godot-rc: add 4.0-rc3

---

bucket/godot-mono-rc.json

Add Godot Release Candidate (Mono version)

godot-mono-rc: add 4.0-rc3

---

bucket/oracle-instant-client-sdk19.json
bucket/oracle-instant-client-sqlplus19.json
bucket/oracle-instant-client19.json

- Relates to https://github.com/ScoopInstaller/Main/pull/4524

oracle-instant-client-sqlplus19: Add version 19.17.0.0.0

---

bucket/dotnet-sdk-lts.json
bucket/dotnet-sdk-preview.json
bucket/dotnet2-sdk.json
bucket/dotnet3-sdk.json
bucket/dotnet5-sdk.json
bucket/dotnet6-sdk.json

- Close https://github.com/ScoopInstaller/Versions/pull/1056

dotnet-sdk: Tweak manifests

---

bucket/miniconda3-4.12.0.json

Relates to https://github.com/ScoopInstaller/Extras/pull/10636
The checkver and autoupdate field has been removed from the manifest.

miniconda3-4.12.0: add version 4.12.0

---

bucket/7zip-beta.json
bucket/7zip-zstd.json

Relates to https://github.com/ScoopInstaller/Extras/issues/10445

7zip-beta|zstd: Persist `Codecs`, `Formats` Folder & Rename shortcuts

---

bucket/kopia-rc.json

Relates to https://github.com/ScoopInstaller/Main/actions/runs/4682561852/jobs/8296568571#step:3:481

kopia-rc: Add version 0.13.0-rc1

---

bucket/inkscape-dev.json

inkscape-dev: Fix `.com` bins, and `checkver`

---

bucket/zig-dev.json

zig-dev: Add 32bit and arm64

---

bucket/espanso-pre.json
bucket/oracle-instant-client19.json
bucket/php80.json
bucket/php81.json
bucket/php82.json
bucket/winget-preview.json
bucket/winget1.4.json
bucket/winget1.5.json

Relates to https://github.com/ScoopInstaller/Extras/pull/11357

(chore): Suggests `extras/vcredist2022`

---

bucket/pwsh-beta.json

Also uses the checksum file for hash extraction
Relates to https://github.com/ScoopInstaller/Main/pull/4837

pwsh-beta: Add arm64

---

bucket/neovim-nightly.json

neovim-nightly: Remove `nvim-qt.exe`

---

bucket/qview-nightly.json

This package was moved from Azure Pipelines to GitHub Actions

qview-nightly: Fix manifest

---

bucket/mpv.net-beta.json

(fix)mpv.net-beta: Fix 'regex','autoupdate'

---

bucket/obs-studio-pre.json

Fixed `checkver` and `autoupdate`

obs-studio-pre: Update to version `30.0.0-rc1`

---

bucket/windowsdesktop-runtime-6.0.json

windowsdesktop-runtime-6.0: Add Version 6.0.25

---

bucket/postgresql15.json

postgresql: Add version 15.5

---

bucket/kicad-nightly.json

kicad-nightly: Fix autoupdate and homepage

---

bucket/kicad-lite-nightly.json

kicad-lite-nightly: Fix autoupdate

---

bucket/openssl-light.json

openssl-light@3.2.0: Update to 3.2.0 and support ARM64

---

bucket/sqlitebrowser-nightly.json

sqlitebrowser-nightly: Remove extract_dir.

---

bucket/strawberry-nightly.json

Relates to https://github.com/ScoopInstaller/Versions/pull/1334#issuecomment-1916243699

strawberry-nightly: Update to version 7679892861

---

bucket/xdman-beta.json

xdman-beta: Fix autoupdate

---

bucket/wixtoolset3.json

Copy from https://github.com/ScoopInstaller/Main/blob/d6bb79cf493c8986174b2df7c477ac4a5df587dc/bucket/wixtoolset.json

wix3: Add version 3.14

---

bucket/obs-studio-pre.json

obs-studio-pre: Fix checkver

---

bucket/scala2.json

scala2: Upgrade scala2 to latest version - 2.13.13

---

bucket/swift-nightly.json

- Relates to https://github.com/ScoopInstaller/Main/pull/5693
- Wait for https://github.com/ScoopInstaller/Scoop/pull/5871 and https://github.com/ScoopInstaller/Main/pull/5552
For the nightly version, there's a simpler script, but I've no time to optimize it.

swift-nightly: Fix install script

---

bucket/r43.json

r43: Add version 4.3.3

---

bucket/sfsu-beta.json

sfsu-beta: Add version 1.11.0-beta.3

---

bucket/geogebra5.json

geogebra5: Update version to 5.2.840.0 and improve autoupdate url

---

bucket/gitbutler-nightly.json

gitbutler-nightly: Add version 0.5.415

---

bucket/openscad-dev.json

openscad-dev: Update to version 2024.05.10

---

bucket/go114.json

Relates to https://github.com/ScoopInstaller/Main/pull/5806

go114: Fix deprecated (un)install warnings

---

bucket/obs-studio-pre.json

Specify obs-studio-pre in shortcut

---

bucket/android-studio-beta.json
bucket/android-studio-canary.json

android-studio: fix checkver

---

bucket/cuda11.7.json
bucket/cuda11.8.json

Closes #1092 #1043
Relates to #1092 #1043

cuda: Add versions 11.7 11.8

---

bucket/mingw-msvcrt.json

See here : [mingw-msvcrt : add version 12.2.0-rt_v10-rev2](https://github.com/ScoopInstaller/Main/pull/4575)

mingw-msvcrt : add version 12.2.0-rt_v10-rev2

---

bucket/maven4-alpha.json
bucket/maven4.json

Add maven4-alpha package
Closes #1681

maven4: Add version 4.0.0-beta-3

---

bucket/systeminformer-nightly.json

systeminformer-nightly: Add au.hash

---

bucket/openscad-dev.json

openscad-dev@2024.07.22: Fix autoupdate.extract_dir

---

bucket/zettlr-nightly.json

Add [Zettlr Nightly](https://nightly.zettlr.com/).
Closes #1173, inherits #1174

zettlr-nightly: Add version 3.2.0

---

bucket/atom-ng.json

i already tested the install and the uninstall and the two are working fine
Closes #XXXX

atom-ng: Add version 1.66.12

---

bucket/explorerplusplus-dev.json

- Relates to https://github.com/ScoopInstaller/Extras/pull/13664

explorerplusplus-dev: Add version 1.5.0.2444

---

bucket/nodejs22.json

nodejs22: Add version 22.11.0

---

bucket/oracle-instant-client-odbc19.json
bucket/oracle-instant-client-odbc21.json
bucket/oracle-instant-client-sdk21.json
bucket/oracle-instant-client-sqlplus21.json
bucket/oracle-instant-client19.json
bucket/oracle-instant-client21.json

oracle-instant-client21: Add version 21.15.0.0.0

---

bucket/python313.json

from python312.json and main bucket python.json

add python313

---

bucket/typora-dev.json

add typora-dev since version 1.9.10-dev

---

bucket/zls-dev.json

Add master version of zls with auto update based on latest zig-dev version
Closes #1503

zls: Add version 0.15.0-dev.3+fedbf31

---

bucket/zed-nightly.json

zed-nightly: update manifest to match new release layout

---

bucket/zed-opengl-nightly.json

chore: fix zed-opengl-nightly bin path

---

bucket/godot-beta.json
bucket/godot-mono-beta.json

- Moving source to godotengine/godot-builds
- Updating manifest to latest beta
Closes #2129

godot-beta, godot-mono-beta fixing source

---

bucket/hadoop-winutils33.json

hadoop-winutils33: Set environment variables per project README

---

bucket/idea-ultimate-latest.json

idea-ultimate-latest : add version 231.8109.90

---

bucket/php84.json

php: Add version 8.4

---

bucket/zotero6.json
scripts/zotero/install-zotero-url-protocol.ps1
scripts/zotero/uninstall-zotero-url-protocol.ps1

zotero6 is no longer updated, but is still available. zotero7 is recommended version.
Relates to https://github.com/ScoopInstaller/Extras/pull/13864 https://github.com/ScoopInstaller/Extras/issues/13821

zotero6: Add zotero6 6.0.36

---

bucket/odin-dev.json
bucket/odin-nightly.json
bucket/odin.json

odin, odin-dev, odin-nightly: make 'shared' directory persistent

---

bucket/gitbutler-nightly.json

gitbutler-nightly: Update shortcuts

---

bucket/komorebi-nightly.json

Add komorebi-nightly

---

bucket/zed-nightly.json
bucket/zed-opengl-nightly.json

zed-nightly + zed-opengl-nightly: switch to zip files + hash file

---

bucket/zed-nightly.json
bucket/zed-opengl-nightly.json

zed-nightly + zed-opengl-nightly: fix version regex

---

bucket/rtools44.json

rtools44: Add version 4.4.6459.6401

---

bucket/wechat-legacy.json

Relates to https://github.com/ScoopInstaller/Extras/pull/15226#issuecomment-2796481579

wechat-legacy: Add version 3.9.12.45

---

bucket/freecad-weekly.json

Update freecad-weekly.json to work with current weekly release file names

---

bucket/typora0.11.18.json

official download link is now unavailable, revert Commit 96b77ce
Closes #XXXX

typora0.11.18: revert url

---

bucket/thorium-avx2.json

Fixes the change that the author made to the repo since he consolidated the versions. Also updates the version to latest since my original PR was from ages ago

thorium-avx2: Update to version 130.0.6723.174 and fix download repo

---

bucket/yazi-nightly.json

yazi: Add version nightly

---

bucket/spotify-qt-nightly.json

Relates to https://github.com/ScoopInstaller/Extras/pull/15372

spotify-qt-nightly: Update to version 4.0.0-dev.0

---

bucket/zig-dev.json

zig-dev: Fix extract_dir (Close #2314)

---

bucket/innounp-unicode.json

If deprecation's preferred, then that should be done.
Fixes https://github.com/ScoopInstaller/Extras/pull/15575#issuecomment-2941409743.

innounp-unicode: Update to version 2.64.4

---

bucket/xournalpp-nightly.json

https://github.com/ScoopInstaller/Versions/issues/2333

Xournal++ Nightly：update checkver
